# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
    - multiple_closures_with_trailing_closure
opt_in_rules: # some rules are turned off by default, so you need to opt-in
included: # paths to include during linting. `--path` is ignored if present.
  - itunes-vip
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)

